spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_manager
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

#  mvc:
#   view:
#    prefix: /WEB-INF/jsp/


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: application

server:
  port: 9090
  servlet:
    context-path: /financial-manager