name: Conditional Auto Merge and Reviewer Assignment

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - content-updates

permissions:
  pull-requests: write
  contents: write

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - '**.md'

  assign-reviewer-hw:
    if: ${{ needs.check-changes.outputs.docs == 'true' }}
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - name: Assign reviewers
        uses: ahmadnassri/action-auto-assign@v2
        with:
          reviewers: AleksandrMSK
          skip-draft: true

  auto-merge-docs:
    if: ${{ needs.check-changes.outputs.docs == 'true' }}
    needs: [check-changes, assign-reviewer-hw]
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
