name: Auto merge content updates

on:
  push:
    branches:
      - content-update

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create PR or Auto-Merge
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          title: "Auto update: docs and README"
          body: "Automated content update."
          allow_no_diff: false
          label: auto-merge
          reviewers: ""
