name: Conditional Auto Merge and Reviewer Assignment

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      hw: ${{ steps.filter.outputs.hw }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'README.md'
            hw:
              - 'HW-*/**'

  assign-reviewer-hw:
    if: ${{ needs.check-changes.outputs.hw == 'true' }}
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - name: Assign reviewers for HW changes
        uses: ahmadnassri/action-auto-assign@v2
        with:
          reviewers: AleksandrMSK
          skip-draft: true

  auto-approve-docs:
    if: ${{ needs.check-changes.outputs.docs == 'true' && needs.check-changes.outputs.hw != 'true' }}
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - name: Auto approve docs PR
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge-docs:
    if: ${{ needs.check-changes.outputs.docs == 'true' && needs.check-changes.outputs.hw != 'true' }}
    needs: [check-changes, auto-approve-docs]
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge for docs PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash