name: Conditional Auto Merge and Reviewer Assignment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      only_docs: ${{ steps.filter.outputs.only_docs }}
    steps:
      - uses: actions/checkout@v3

      - id: filter
        name: Check changed files
        run: |
          echo "::group::Detecting changes..."
          FILES=$(git diff --name-only origin/main)
          echo "$FILES"
          echo "::endgroup::"
          
          ONLY_DOCS=true
          for file in $FILES; do
            if [[ "$file" =~ ^(\.github/|docs/|README\.md)$ || "$file" =~ ^(\.github/|docs/|README\.md)/.* ]]; then
              continue
            else
              ONLY_DOCS=false
              break
            fi
          done
          echo "only_docs=$ONLY_DOCS" >> "$GITHUB_OUTPUT"

  assign-reviewer-hw:
    needs: check-changes
    if: needs.check-changes.outputs.only_docs == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewer
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['AleksandrMSK']
            });

  auto-merge-docs:
    needs: check-changes
    if: needs.check-changes.outputs.only_docs == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
